"""Plug-and-play interfaces as structural Protocols.

Any object with the right methods conforms — no inheritance required. This is
what makes modules swappable: users pass their own Embedder / VectorStore /
Retriever / etc. into RagPipeline.
"""
from __future__ import annotations

from typing import Iterator, Protocol, runtime_checkable

from rag.types import ChunkRecord, SearchResult


@runtime_checkable
class Embedder(Protocol):
    def embed(self, texts: list[str]) -> list[list[float]]: ...


@runtime_checkable
class EntityExtractor(Protocol):
    def extract(self, text: str) -> list[str]: ...


@runtime_checkable
class CacheStore(Protocol):
    def get(self, key: str) -> object | None: ...
    def set(self, key: str, value: object, ttl_seconds: float | None = None) -> None: ...
    def items(self) -> list: ...
    def clear(self) -> None: ...


@runtime_checkable
class VectorStore(Protocol):
    def add(self, records: list[ChunkRecord]) -> None: ...
    def query(self, embedding: list[float], top_k: int, where: dict | None = None) -> list[SearchResult]: ...
    def get_all(self) -> list[ChunkRecord]: ...
    def delete_source(self, source_key: str) -> None: ...
    def count(self) -> int: ...
    def list_sources(self) -> list[dict]: ...
    def get_source_hash(self, source_key: str) -> str | None: ...
    def touch_source(self, source_key: str, fetched_at: str) -> None: ...


@runtime_checkable
class KeywordIndex(Protocol):
    def build(self, records: list[ChunkRecord]) -> None: ...
    def search(self, query: str, top_k: int) -> list[SearchResult]: ...


@runtime_checkable
class Retriever(Protocol):
    def retrieve(self, query: str, top_k: int) -> list[SearchResult]: ...


@runtime_checkable
class Reranker(Protocol):
    def rerank(self, query: str, results: list[SearchResult], top_k: int) -> list[SearchResult]: ...


@runtime_checkable
class Generator(Protocol):
    def generate(self, messages: list[dict], system: str = "", max_tokens: int | None = None) -> str: ...
    def stream(self, messages: list[dict], system: str = "", max_tokens: int | None = None) -> Iterator[str]: ...
